import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          Jansora's Document
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Wrote By {' Jansora '}

            </a>
          </div>
        </div>

        <div className={styles.center}>
          
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>

          <Link href={"/project/kong-upgrade/kong-install"}  className={styles.card}>
            <h3 className={inter.className}>
              项目管理 <span>-&gt;</span>
            </h3>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </Link>

          <Link href={"/development/qa/api-doc"}  className={styles.card}>
            <h3 className={inter.className}>
              研发环境 <span>-&gt;</span>
            </h3>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </Link>

          <Link href={"/linked/development/system"}  className={styles.card}>
            <h3 className={inter.className}>
              资源索引 <span>-&gt;</span>
            </h3>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </Link>

          <Link href={"/new-comers/first-day"}  className={styles.card}>
            <h3 className={inter.className}>
              新人必读 <span>-&gt;</span>
            </h3>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </Link>

        </div>
      </main>
    </>
  )
}
