FROM registry.cn-hongkong.aliyuncs.com/jansora/elasticsearch:8.7.0
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install https://jansora.oss-cn-shanghai.aliyuncs.com/files/es/8.7.0/elasticsearch-analysis-ik-8.7.0.zip --batch
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install https://jansora.oss-cn-shanghai.aliyuncs.com/files/es/8.7.0/elasticsearch-analysis-pinyin-8.7.0.zip --batch
