worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    server {
        listen       80;
        server_name  _;

        # 允许所有域名的跨域请求
        add_header 'Access-Control-Allow-Origin' '*' always;

        # 如果需要支持其他的请求方法，比如 PUT, DELETE 等，可以配置以下头
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;

        # 如果需要支持某些特定的请求头，可以加上这个
        # add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

        # 预检请求的缓存时间（单位：秒）
        add_header 'Access-Control-Max-Age' '3600' always;

        # 根路径显示主页
        location / {
            root /static;

            autoindex on; # 开启目录文件列表
            autoindex_exact_size on; # 显示出文件的确切大小，单位是bytes
            autoindex_localtime on; # 显示的文件时间为文件的服务器时间
            charset utf-8,gbk; # 避免中文乱码
        }
    }

    include /etc/nginx/conf.d/*.conf;

}
