name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Apt install proxytunnel
        run: |
          sudo apt install proxytunnel sshpass -y


      - name: Compile Spring Boot
        run: |
          sshpass -p '${{ secrets.DEPLOYMENT_HOST_PASSWORD }}' ssh -o 'ProxyCommand=proxytunnel -p worker2.kubernetes.jansora.com:3389 -P doudizhu:doudizhu -d %h:%p' root@127.0.0.1 -p 23722 -o StrictHostKeyChecking=no "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/ && cd /data/ci/Github/galaxy/backend/ && git pull && /root/.sdkman/candidates/mvnd/current/bin/mvnd --settings ../deploy/settings.xml install "

      - name: Build Image
        run: |
          sshpass -p '${{ secrets.DEPLOYMENT_HOST_PASSWORD }}' ssh -o 'ProxyCommand=proxytunnel -p worker2.kubernetes.jansora.com:3389 -P doudizhu:doudizhu -d %h:%p' root@127.0.0.1 -p 23722 -o StrictHostKeyChecking=no "cd /data/ci/Github/galaxy/deploy/ && bash image.sh v1 "

      - name: Push Image
        run: |
          sshpass -p '${{ secrets.DEPLOYMENT_HOST_PASSWORD }}' ssh -o 'ProxyCommand=proxytunnel -p worker2.kubernetes.jansora.com:3389 -P doudizhu:doudizhu -d %h:%p' root@127.0.0.1 -p 23722 -o StrictHostKeyChecking=no "cd /data/ci/Github/galaxy/deploy/ && bash push.sh v1 "

      - name: Redeploy
        run: |
          sshpass -p '${{ secrets.DEPLOYMENT_HOST_PASSWORD }}' ssh root@master.kubernetes.jansora.com -o StrictHostKeyChecking=no "export KUBECONFIG=/etc/kubernetes/admin.conf &&  kubectl rollout restart deployment/hole-prod deployment/space-prod deployment/insight-prod deployment/mars-prod   --insecure-skip-tls-verify=true "
      
